backend:
  name: git-gateway
  branch: master

media_folder: "public/assets/images" # Location where files will be stored in the repo
public_folder: "public/assets/images" # The src attribute for uploaded media

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/data/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Photo, name: photo, widget: image }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: "Home Page"
        name: "home"
        file: "src/data/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }

          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { name: "alertText", label: "Alert Text", widget: "string" }
              - { name: "alertLinkText", label: "Alert Link Text", widget: "string" }
              - { name: "alertLinkHref", label: "Alert Link Href", widget: "string" }
              - { name: "heading", label: "Heading", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }
              - { name: "primaryButtonText", label: "Primary Button Text", widget: "string" }
              - { name: "primaryButtonHref", label: "Primary Button Href", widget: "string" }
              - { name: "secondaryButtonText", label: "Secondary Button Text", widget: "string" }
              - { name: "secondaryButtonHref", label: "Secondary Button Href", widget: "string" }
              - { name: "imageUrl", label: "Image URL", widget: "image" }

          - label: "Trusted By"
            name: "trustedBy"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - { name: "src", label: "Image Source", widget: "image" }
                  - { name: "alt", label: "Alt Text", widget: "string" }
          - label: "Features"
            name: "features"
            widget: "object"
            fields:
              - { name: "sectionTitle", label: "Section Title", widget: "string" }
              - { name: "sectionSubtitle", label: "Section Subtitle", widget: "string" }
              - { name: "sectionDescription", label: "Section Description", widget: "text" }
              - label: "Services"
                name: "services"
                widget: "list"
                fields:
                  - { name: "title", label: "Service Title", widget: "string" }
                  - { name: "description", label: "Service Description", widget: "text" }
                  - { name: "linkText", label: "Link Text", widget: "string" }
                  - { name: "linkHref", label: "Link Href", widget: "string" }
                  - { name: "imgSrc", label: "Image Source", widget: "image" }
                  - { name: "imgAlt", label: "Image Alt Text", widget: "string" }